basePath: "8081"
definitions:
  controller._ResponsePost:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  controller._ResponsePostList:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  controller._ResponseSuccess:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
host: '127.0.0.1:'
info:
  contact: {}
  description: 加油开发<h1>p神</h1>
  termsOfService: http://swagger.io/terms/
  title: Dimension_Door 接口文档
paths:
  /apply/:id:
    get:
      consumes:
      - application/json
      description: 用户完成对具体讲座的报名并返回结果
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller._ResponseSuccess'
      security:
      - ApiKeyAuth: []
      summary: 用户报名讲座接口
      tags:
      - 报名
  /cancel/:id:
    get:
      consumes:
      - application/json
      description: 用户取消报名
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller._ResponseSuccess'
      security:
      - ApiKeyAuth: []
      summary: 用户取消报名
      tags:
      - 取消报名
  /delete/:id:
    get:
      consumes:
      - application/json
      description: 管理员删除讲座信息
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller._ResponseSuccess'
      security:
      - ApiKeyAuth: []
      summary: 删除讲座信息
      tags:
      - 删除
  /login:
    post:
      consumes:
      - application/json
      description: 完成用户的登录并返回Token
      parameters:
      - description: 微信临时令牌
        in: query
        name: code
        type: string
      - description: 用户性别（默认0）
        in: query
        name: gender
        type: integer
      - description: 用户头像
        in: query
        name: picture
        type: string
      - description: 用户名
        in: query
        name: username
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller._ResponseSuccess'
      security:
      - ApiKeyAuth: []
      summary: 用户登录接口
      tags:
      - 登录
  /post:
    post:
      consumes:
      - application/json
      description: 管理员账号发布讲座的信息，其中关于id的字段不要暴露给用户操作，点赞数量，已报名人数都不可暴露
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - in: query
        name: can_delete
        type: integer
      - in: query
        name: create_time
        type: string
      - description: 点赞数量
        in: query
        name: like_nums
        type: integer
      - description: 讲座限制人数
        in: query
        name: num_limit
        required: true
        type: integer
      - description: 帖子id
        in: query
        name: post_id
        type: integer
      - description: 讲座内容简介
        in: query
        name: post_introduction
        type: string
      - description: 讲座图片(后期可以放一张图片作为默认值，放入静态资源）
        in: query
        name: post_picture
        type: string
      - description: 讲座地点
        in: query
        name: post_position
        required: true
        type: string
      - description: 讲座开始时间
        in: query
        name: post_time
        required: true
        type: string
      - description: 讲座标题
        in: query
        name: post_title
        required: true
        type: string
      - description: 讲座报名人数
        in: query
        name: posted_nums
        type: integer
      - description: 校验id
        in: query
        name: tea_verify_id
        type: string
      - in: query
        name: teacher_id
        type: integer
      - description: 教师简介
        in: query
        name: teacher_intro
        type: string
      - description: 教师姓名
        in: query
        name: teacher_name
        required: true
        type: string
      - description: 教师专业
        in: query
        name: teacher_professional
        type: string
      - description: 教师学校
        in: query
        name: teacher_school
        type: string
      - description: 校验id
        in: query
        name: verify_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller._ResponseSuccess'
      security:
      - ApiKeyAuth: []
      summary: 发布讲座信息
      tags:
      - 发布
  /post/:id:
    get:
      consumes:
      - application/json
      description: 查询单个讲座详情
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller._ResponsePost'
      security:
      - ApiKeyAuth: []
      summary: 查询详情
      tags:
      - 查询讲座信息
  /posts:
    get:
      consumes:
      - application/json
      description: 展示一页讲座列表,参数中order只有两个值可以选（time、score）目前score还未实现（4.13），size和page表示第几页展示size条记录
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - in: query
        name: order
        type: string
      - in: query
        name: page
        type: integer
      - in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller._ResponsePostList'
      security:
      - ApiKeyAuth: []
      summary: 查看讲座列表
      tags:
      - 查询讲座信息
swagger: "2.0"
